### ISSUE TITLE
Derivative functions for grids with topology

### ISSUE THREAD

**Issue by MaceKuailv** [malmans2/oceanspy#225]
* OceanSpy version:0.20

### Description

One of the attribute of the oceandataset is "face_connections", which essentially describes which tile is connected to which tile and helps us create the od._grid xgcm object. 

A lot of the compute functions is based on `grid.diff` function. However, when I do this for ECCO grid:

```
dnum = od._grid.diff(
                od._ds['UVELMASS'],axis = 'X', boundary="fill", fill_value=np.nan
            )
```
There is an error message: ValueError: 'Yp1' not found in array dimensions ('time', 'Z', 'face', 'Y', 'Xp1'). The gird object look quite healthy to me.
```
<xgcm.Grid>
Z Axis (not periodic, boundary=None):
  * center   Z --> left
  * left     Zl --> center
  * outer    Zp1 --> center
  * right    Zu --> center
Y Axis (not periodic, boundary=None):
  * center   Y --> right
  * right    Yp1 --> center
time Axis (not periodic, boundary=None):
  * center   time_midp --> outer
  * outer    time --> center
X Axis (not periodic, boundary=None):
  * center   X --> right
  * right    Xp1 --> center
```
According to the documentation of xgcm (https://xgcm.readthedocs.io/en/latest/grid_topology.html), it should work. So I think either there is a bug in the part where we create the grid object or xgcm actually does not support derivative and interpolation on ECCO grid. There is actually a example notebook they made (https://github.com/xgcm/xgcm-examples/blob/master/01_eccov4.ipynb), but they didn't use the function though.

**Comment by Mikejmnez** [comment]
The problem when dealing with the complex topology of the ECCO is that UVELMASS for ```faces>=6 ``` is not really UVELMASS, the same thing with VVELMASS, in the way that we associate u with longitudinal and northward velocities. But these two are vector pairs and the `xgcm.Grid` object does know how to take derivatives when dealing with complex topology (with the correct face_connection passed as an argument when defining the Grid object). 


The correct way to calculate derivatives in the case of dealing with complex topologies is to pass the vector pair (mates) (UVELMASS, VVELMASS) as argument when calculating the gradients. This is done via `grid.diff_2d_vector`, and this is the way it is also done in the notebook example you are referring to (cell 19):

```python
diff_ADV_th = grid.diff_2d_vector({'X': advx_th_vint, 'Y': advy_th_vint}, boundary='fill')
```

the variable `diff_ADV_th` is a vector with x and y components, each associated with the correct `X` and `Y` derivatives of the fluxes that are passed as arguments. The divergence/convergence of the fluxes is calculated in the following line within the same cell:

```python
conv_ADV_th = -diff_ADV_th['X'] - diff_ADV_th['Y']
```

**Comment by Mikejmnez** [comment]
The problem with ```xgcm.Grid``` has been the need to interpolate across faces (in particular interpolation at corner G points), a feature that I am not entirely sure has been resolved (it is pretty involved, since `xgcm.Grid` already has a huge API). The way `oceanspy` gets rid of this issue is by transforming the dataset (lazily) and removing face as a dimension. With that, you can calculate derivatives and interpolate with no issue.

**Comment by MaceKuailv** [comment]
I have tried that function as well. However it is only giving me $\frac{du}{dx}$. The non-diagonal components of velocity gradient tensor is not computed. If I switch X and Y in the dictionary that got passed into the diff_2D_velocity function, I would got a similar error. I think what I should be getting is du/dy being defined on the corner node. After all, if one only looks at u component of the velocity as a scaler, it should be the same as the other quantities like Theta. 

@asiddi24 has showed me how to do the derivative after the transformation. Although the transformation is done lazily, when we are doing a derivative, there is no escaping calculating the entire thing. I think this is too big a computation to perform. 

Another reason I think we need to implement something to solve this issue is that
```
od.compute.gradient(varNameList = 'THETA')
```
also doesn't work.

**Comment by Mikejmnez** [comment]
> I have tried that function as well. However it is only giving me $\frac{du}{dx}$. The non-diagonal components of velocity gradient tensor is not computed. If I switch X and Y in the dictionary that got passed into the diff_2D_velocity function, I would got a similar error. I think what I should be getting is du/dy being defined on the corner node. After all, if one only looks at u component of the velocity as a scaler, it should be the same as the other quantities like Theta.
> 

Yes, this is correct. With `xgcm.Grid` and complex topology, there are issues with corner points across faces.


> @asiddi24 has showed me how to do the derivative after the transformation. Although the transformation is done lazily, when we are doing a derivative, there is no escaping calculating the entire thing. I think this is too big a computation to perform.
> 

Are you using ECCO? Calculating the relative vorticity should be very straightforward even for the whole domain. For the LLC4320 this can be a problem indeed, so for that larger dataset is would be advantageous to have grid.diff be able to handle corner points ( and so would the interpolating function).

 I guess I just don't know what exactly you are doing. But if @asiddi24 is helping you / guiding you I defer to him  :)


> Another reason I think we need to implement something to solve this issue is that
> 
> ```
> od.compute.gradient(varNameList = 'THETA')
> ```
> 
> also doesn't work.

Is `od` the original dataset? In that way, yes, the gradient calculation is going to fail because it `xcgm.Grid` is incomplete, in the sense that it cannot handle the complete 3D gradient across faces...

One thing, `oceanspy` uses/calls `xgcm.Grid` to calculate derivatives. The issue is then about developing `xgcm.Grid` in order to allow the correct handling of the gradient function in complex topologies. I would then recommend working at the xgcm level, rather than the oceanspy level.

**Comment by MaceKuailv** [comment]
Yes, that's right. 

> So I think either there is a bug in the part where we create the grid object or xgcm actually does not support derivative and interpolation on ECCO grid. 

I guess the latter is true then. I want to analyze the

**Comment by MaceKuailv** [comment]
Yes, that's right.

So I think either there is a bug in the part where we create the grid object or xgcm actually does not support derivative and interpolation on ECCO grid.

I guess the latter is true then. I guess we can worry about LLC4320 some other time
